package com.bangla.shobdojot.data

import com.bangla.shobdojot.model.Level

/**
 * Level content, in teaching order: plain letters first, then one vowel sign at a time, then
 * several signs together, then conjuncts one family at a time, then everything mixed. Puzzle
 * difficulty (tiles, word count, longest word, rarity) only orders levels within a block.
 *
 * Every word is attested in real Bengali text (checked against corpus frequency data) and
 * hand-picked from a vocabulary curated for a child - frequency alone offers verb inflections,
 * word fragments and newspaper register, none of which teach a beginner anything. Each
 * `letters` entry is one akshara: the unit that sits on a wheel tile and fills one grid cell.
 *
 * `teaches` is what this level introduces that no earlier level used - a letter, a vowel sign,
 * or a conjunct - so the app can show it before the board.
 *
 * Two rules constrain what can go here, and `LevelsTest` enforces both:
 *  - a word must be spellable from the tiles using each tile at most once, and every tile
 *    must be used by some word, so the wheel never holds a letter the player cannot spend;
 *  - the words must form a connected crossword. Only two words can pass through one cell,
 *    so three words sharing nothing but the same akshara cannot all be placed: in
 *    চার / কার / চাবি / চাকা, three of the four meet only at চা.
 *
 * `extras` are words the same tiles can spell that are not on the board; finding one fills
 * the chest instead of the grid.
 *
 * Generated by tools/build.py from tools/catalogue.py - do not edit by hand.
 */
object Levels {

    val all: List<Level> = listOf(
        // Block 1, plain letters: consonants and independent vowels on their own, no signs at all.
        Level(1, listOf("ক", "ল", "ম"), listOf("কলম", "কম", "কল"), block = 1, teaches = listOf("ল", "ক", "ম")),
        Level(2, listOf("ক", "ল", "ম", "আ"), listOf("কলম", "কম", "কল", "আম"), block = 1, teaches = listOf("আ")),
        Level(3, listOf("ক", "ল", "ম", "এ"), listOf("কলম", "এক", "কম", "কল"), block = 1, teaches = listOf("এ")),
        Level(4, listOf("ক", "ল", "ম", "ফ"), listOf("কলম", "কম", "কল", "ফল"), block = 1, teaches = listOf("ফ")),
        Level(5, listOf("ক", "ল", "ম", "অ", "ত"), listOf("কলম", "অতল", "কম", "কল"), block = 1, teaches = listOf("অ", "ত"), extras = listOf("তল")),
        Level(6, listOf("ব", "দ", "ল"), listOf("বদল", "দল", "বল"), block = 1, teaches = listOf("ব", "দ")),
        Level(7, listOf("ব", "দ", "ল", "ঈ"), listOf("বদল", "দল", "বল", "ঈদ"), block = 1, teaches = listOf("ঈ")),
        Level(8, listOf("ব", "ল", "স"), listOf("বল", "সব", "বস"), block = 1, teaches = listOf("স")),
        Level(9, listOf("স", "ব", "ই"), listOf("সব", "বই", "বস"), block = 1, teaches = listOf("ই")),
        Level(10, listOf("স", "ব", "র"), listOf("সব", "রস", "বস"), block = 1, teaches = listOf("র"), extras = listOf("সর")),
        Level(11, listOf("ঈ", "গ", "ল", "দ"), listOf("ঈগল", "দল", "ঈদ"), block = 1, teaches = listOf("গ")),
        Level(12, listOf("গ", "র", "ম", "ক"), listOf("গরম", "কম", "কর", "গম"), block = 1),
        Level(13, listOf("ন", "গ", "র", "ম"), listOf("মন", "গম", "নগর", "গরম"), block = 1, teaches = listOf("ন"), extras = listOf("নরম")),
        Level(14, listOf("ব", "দ", "ল", "শ"), listOf("বদল", "দল", "বল", "দশ"), block = 1, teaches = listOf("শ")),
        Level(15, listOf("জ", "ল", "ন"), listOf("জল", "জন", "নল"), block = 1, teaches = listOf("জ")),
        Level(16, listOf("অ", "জ", "গ", "র", "ন"), listOf("অজগর", "নগর", "জন"), block = 1),
        Level(17, listOf("ও", "জ", "ন", "ল"), listOf("ওজন", "জন", "জল", "নল"), block = 1, teaches = listOf("ও")),
        Level(18, listOf("ধ", "ন", "ব", "ল"), listOf("ধন", "বন", "বল"), block = 1, teaches = listOf("ধ"), extras = listOf("নল")),
        Level(19, listOf("স", "ব", "ড়"), listOf("সব", "বড়", "বস"), block = 1, teaches = listOf("ড়")),
        Level(20, listOf("ব", "ড়", "ঝ", "ন"), listOf("বড়", "ঝড়", "বন"), block = 1, teaches = listOf("ঝ")),
        Level(21, listOf("স", "ব", "য"), listOf("সব", "বস", "যব"), block = 1, teaches = listOf("য")),
        Level(22, listOf("ক", "ম", "ট", "উ"), listOf("কম", "টক", "উট"), block = 1, teaches = listOf("উ", "ট")),
        Level(23, listOf("ল", "ব", "ণ", "ঋ"), listOf("ঋণ", "লবণ", "বল"), block = 1, teaches = listOf("ঋ", "ণ")),
        Level(24, listOf("ঔ", "ষ", "ধ", "ন", "ল"), listOf("ঔষধ", "ধন", "নল"), block = 1, teaches = listOf("ঔ", "ষ")),

        // Block 2, one vowel sign: a single vowel sign per level, introduced one at a time in KAR_ORDER.
        Level(25, listOf("লা", "ল", "ক"), listOf("লাল", "কল", "কলা"), block = 2, teaches = listOf("া")),
        Level(26, listOf("লা", "ল", "ফ"), listOf("লাল", "ফল", "লাফ"), block = 2),
        Level(27, listOf("ক", "ল", "কা"), listOf("কল", "কাল", "কাক"), block = 2),
        Level(28, listOf("কা", "ল", "ন"), listOf("কাল", "কান", "নল"), block = 2),
        Level(29, listOf("ক", "ম", "লা"), listOf("কমলা", "কম", "কলা"), block = 2),
        Level(30, listOf("না", "ট", "ক", "আ"), listOf("নাটক", "আট", "টক"), block = 2),
        Level(31, listOf("গা", "ন", "কা", "ল"), listOf("গান", "কাল", "কান", "নল"), block = 2),
        Level(32, listOf("স", "কা", "ল", "ব"), listOf("সকাল", "সব", "বল", "কাল", "বস"), block = 2),
        Level(33, listOf("জা", "না", "লা", "ম"), listOf("জাম", "নাম", "মজা", "নালা", "জানালা"), block = 2),
        Level(34, listOf("ক", "লা", "গা", "ছ"), listOf("কলা", "লাগা", "গাছ", "কলাগাছ"), block = 2, teaches = listOf("ছ")),
        Level(35, listOf("ব", "ই", "খা", "তা"), listOf("বই", "খাই", "খাতা"), block = 2, teaches = listOf("খ")),
        Level(36, listOf("খা", "তা", "ক", "লা"), listOf("খাতা", "কলা", "খালা"), block = 2, extras = listOf("তাক")),
        Level(37, listOf("ভা", "ই", "ব", "ত"), listOf("ভাই", "বই", "ভাত"), block = 2, teaches = listOf("ভ")),
        Level(38, listOf("ঊ", "ষা", "ভা", "ত"), listOf("ঊষা", "ভাষা", "ভাত"), block = 2, teaches = listOf("ঊ")),
        Level(39, listOf("ক", "ম", "লা", "থা"), listOf("থালা", "কমলা", "কম", "কলা"), block = 2, teaches = listOf("থ")),
        Level(40, listOf("মা", "ছ", "রা", "ঙা"), listOf("মাছ", "মারা", "রাঙা", "মাছরাঙা"), block = 2, teaches = listOf("ঙ")),
        Level(41, listOf("ব", "দ", "ল", "ঢা"), listOf("ঢাল", "বল", "বদল", "দল"), block = 2, teaches = listOf("ঢ")),
        Level(42, listOf("গা", "ঢ়", "ন", "কা"), listOf("গাঢ়", "গান", "কান"), block = 2, teaches = listOf("ঢ়")),
        Level(43, listOf("স", "ব", "জি"), listOf("সবজি", "সব", "বস"), block = 2, teaches = listOf("ি")),
        Level(44, listOf("দি", "ন", "জ", "ল"), listOf("দিন", "জন", "জল", "নল"), block = 2),
        Level(45, listOf("তি", "ন", "জ", "ল"), listOf("তিন", "জন", "জল", "নল"), block = 2, extras = listOf("তিল")),
        Level(46, listOf("ঘ", "ড়ি", "ক", "র"), listOf("ঘড়ি", "কর", "ঘর"), block = 2, teaches = listOf("ঘ")),
        Level(47, listOf("ক", "ল", "ম", "ডি"), listOf("ডিম", "কম", "কলম", "কল"), block = 2, teaches = listOf("ড")),
        Level(48, listOf("মে", "ঘ", "র", "স"), listOf("মেঘ", "ঘর", "রস", "সর"), block = 2, teaches = listOf("ে")),
        Level(49, listOf("ক", "ল", "ম", "তে"), listOf("তেল", "কলম", "কম", "কল"), block = 2),
        Level(50, listOf("আ", "পে", "ল", "ট"), listOf("আপেল", "আট", "পেট"), block = 2, teaches = listOf("প")),
        Level(51, listOf("পা", "হা", "ড়"), listOf("পাড়", "হাড়", "পাহাড়"), block = 2, teaches = listOf("হ")),
        Level(52, listOf("হা", "ত", "পা", "খা"), listOf("হাত", "খাত", "পাত", "পাখা", "হাতপাখা"), block = 2),
        Level(53, listOf("পা", "ঠ", "শা", "লা"), listOf("পাঠ", "পালা", "পাশা", "পাঠশালা"), block = 2, teaches = listOf("ঠ")),
        Level(54, listOf("দু", "ই", "ব", "ধ"), listOf("দুই", "বই", "দুধ"), block = 2, teaches = listOf("ু")),
        Level(55, listOf("গ", "রু", "আ", "ম"), listOf("গরু", "আম", "গম"), block = 2),
        Level(56, listOf("ক", "ল", "ম", "ফু"), listOf("ফুল", "কলম", "কম", "কল"), block = 2),
        Level(57, listOf("ক", "ল", "ম", "ঘু"), listOf("ঘুম", "কলম", "কম", "কল"), block = 2),
        Level(58, listOf("ফু", "ট", "ব", "ল"), listOf("বল", "ফুল", "ফুট", "ফুটবল"), block = 2),
        Level(59, listOf("ব", "দ", "ল", "চু"), listOf("চুল", "বদল", "দল", "বল"), block = 2, teaches = listOf("চ")),
        Level(60, listOf("ক", "ল", "ম", "মূ"), listOf("কলম", "কম", "মূল", "কল"), block = 2, teaches = listOf("ূ")),
        Level(61, listOf("ক", "ল", "ম", "তৈ"), listOf("কলম", "কম", "কল", "তৈল"), block = 2, teaches = listOf("ৈ")),
        Level(62, listOf("কৃ", "ষ", "ক", "ল", "ম"), listOf("কৃষক", "কলম", "কম", "কল"), block = 2, teaches = listOf("ৃ")),
        Level(63, listOf("ক", "ম", "লা", "বাং"), listOf("কমলা", "বাংলা", "কম", "কলা"), block = 2, teaches = listOf("ং")),
        Level(64, listOf("ব", "দ", "ল", "চাঁ"), listOf("চাঁদ", "বদল", "দল", "বল"), block = 2, teaches = listOf("ঁ")),

        // Block 3, vowel signs together: several signs in one word, all of them already taught.
        Level(65, listOf("ক", "বি", "তা"), listOf("কবি", "তাক", "কবিতা"), block = 3),
        Level(66, listOf("ফু", "ল", "চা", "কু"), listOf("ফুল", "চাল", "চাকু"), block = 3),
        Level(67, listOf("মে", "ঘ", "লা"), listOf("মেঘ", "মেলা", "মেঘলা"), block = 3),
        Level(68, listOf("দি", "ন", "রা", "ত"), listOf("দিন", "রাত", "দিনরাত"), block = 3),
        Level(69, listOf("হা", "ত", "ঘ", "ড়ি"), listOf("হাত", "ঘড়ি", "হাতঘড়ি"), block = 3),
        Level(70, listOf("দু", "ধ", "ভা", "ত"), listOf("দুধ", "ভাত", "দুধভাত"), block = 3),
        Level(71, listOf("মা", "টি", "র", "পা"), listOf("মাটি", "পার", "পাটি", "মাটির"), block = 3),
        Level(72, listOf("প", "ড়া", "লে", "খা"), listOf("পড়া", "লেখা", "খাড়া", "পড়ালেখা"), block = 3),
        Level(73, listOf("প", "রি", "বা", "র"), listOf("পর", "বার", "বাপ", "পরি", "পরিবার"), block = 3),
        Level(74, listOf("ঘ", "র", "বা", "ড়ি"), listOf("ঘর", "বাঘ", "ঘড়ি", "বাড়ি", "ঘরবাড়ি"), block = 3, extras = listOf("বার")),
        Level(75, listOf("ফু", "ল", "বা", "গা", "ন"), listOf("ফুল", "গান", "বাগান", "ফুলবাগান", "নল"), block = 3),
        Level(76, listOf("পা", "য়ে", "স"), listOf("পাস", "পায়ে", "পায়েস"), block = 3, teaches = listOf("য়")),
        Level(77, listOf("ন", "দী", "র", "পা"), listOf("নদী", "পার", "পান", "নদীর"), block = 3, teaches = listOf("ী")),
        Level(78, listOf("শী", "ত", "কা", "ল"), listOf("তল", "শীত", "কাল", "শীতল", "শীতকাল"), block = 3),
        Level(79, listOf("নৌ", "কা", "ক", "ম"), listOf("নৌকা", "কম", "কাক"), block = 3, teaches = listOf("ৌ")),

        // Block 4, conjuncts: joined consonants, one cluster family at a time.
        Level(80, listOf("ব", "স", "ন্ত"), listOf("সব", "বস", "বসন্ত"), block = 4, teaches = listOf("ন্ত")),
        Level(81, listOf("আ", "গু", "ন", "ন্দ", "ম"), listOf("আগুন", "আনন্দ", "আম"), block = 4, teaches = listOf("ন্দ"), extras = listOf("মন")),
        Level(82, listOf("রা", "স্তা", "ঘা", "ট"), listOf("রাস্তা", "ঘাট", "রাস্তাঘাট"), block = 4, teaches = listOf("স্ত")),
        Level(83, listOf("ক", "ল", "ম", "স্কু"), listOf("কলম", "কম", "স্কুল", "কল"), block = 4, teaches = listOf("স্ক")),
        Level(84, listOf("গ", "র", "ম", "ল্প"), listOf("গরম", "গল্প", "গম"), block = 4, teaches = listOf("ল্প")),
        Level(85, listOf("শি", "ল্প", "ক", "লা"), listOf("কলা", "শিলা", "শিল্প", "শিল্পকলা"), block = 4),
        Level(86, listOf("দি", "ন", "রা", "ত", "ন্না"), listOf("দিনরাত", "দিন", "রাত", "রান্না"), block = 4, teaches = listOf("ন্ন")),
        Level(87, listOf("ব", "ন", "ধ", "ন্ধু"), listOf("বন", "ধন", "বন্ধু"), block = 4, teaches = listOf("ন্ধ")),
        Level(88, listOf("বা", "লি", "শ", "ক্ত"), listOf("বালিশ", "শক্ত", "বালি"), block = 4, teaches = listOf("ক্ত")),
        Level(89, listOf("আ", "পে", "ল", "ন্সি", "ট"), listOf("আপেল", "পেন্সিল", "আট", "পেট"), block = 4, teaches = listOf("ন্স")),
        Level(90, listOf("ব", "দ", "ল", "স্বা"), listOf("বদল", "দল", "বল", "স্বাদ"), block = 4, teaches = listOf("স্ব")),
        Level(91, listOf("ব", "র্ষা", "কা", "ল"), listOf("বর্ষাকাল", "বল", "কাল", "বর্ষা"), block = 4, teaches = listOf("র্ষ")),
        Level(92, listOf("চি", "ঠি", "প", "ত্র", "ছা"), listOf("চিঠিপত্র", "ছাত্র", "চিঠি"), block = 4, teaches = listOf("ত্র")),
        Level(93, listOf("শি", "ক্ষ", "ক", "র"), listOf("কর", "কক্ষ", "শিক্ষক"), block = 4, teaches = listOf("ক্ষ")),
        Level(94, listOf("স", "মু", "দ্র", "ব"), listOf("সমুদ্র", "সব", "বস"), block = 4, teaches = listOf("দ্র")),
        Level(95, listOf("ক", "ম", "লা", "গ্রা"), listOf("কমলা", "কম", "গ্রাম", "কলা"), block = 4, teaches = listOf("গ্র")),
        Level(96, listOf("বি", "দ্যা", "ল", "য়"), listOf("বিল", "লয়", "বিদ্যা", "বিদ্যালয়"), block = 4, teaches = listOf("দ্য")),
        Level(97, listOf("জ", "ন্ম", "দি", "ন"), listOf("জন", "দিন", "জন্ম", "জন্মদিন"), block = 4, teaches = listOf("ন্ম")),
        Level(98, listOf("র", "স", "গো", "ল্লা"), listOf("রস", "সর", "রসগোল্লা"), block = 4, teaches = listOf("ো", "ল্ল")),
        Level(99, listOf("ঐ", "ক্য", "বা", "টি"), listOf("ঐক্য", "বাক্য", "বাটি"), block = 4, teaches = listOf("ঐ", "ক্য")),

        // Block 5, free play: everything taught, mixed, longest words and fullest boards.
        Level(100, listOf("বা", "ল", "তি"), listOf("বাতি", "তিল", "বালতি"), block = 5),
        Level(101, listOf("স", "কা", "ল", "ব"), listOf("সকাল", "সব", "বল", "কাল"), block = 5, extras = listOf("বস")),
        Level(102, listOf("ক", "ল", "ম", "লা", "গ্রা"), listOf("কলম", "কমলা", "গ্রাম", "লাল"), block = 5, extras = listOf("কম", "কল", "কলা")),
        Level(103, listOf("ভা", "লো", "বা", "সা"), listOf("ভালো", "বাসা", "ভাসা", "ভাবা", "ভালোবাসা"), block = 5),
        Level(104, listOf("বি", "চা", "র", "কা"), listOf("চার", "কার", "রবি", "চাবি", "চাকা", "বিচার"), block = 5),
        Level(105, listOf("হা", "স", "পা", "তা", "ল", "টি"), listOf("হাসপাতাল", "পাটি", "পাতাল", "হাতা", "তাল", "পাস"), block = 5, extras = listOf("পাতা"))
    )

    val count: Int get() = all.size

    fun byId(id: Int): Level? = all.firstOrNull { it.id == id }
}
