package com.bangla.shobdojot.data

import com.bangla.shobdojot.model.Level

/**
 * Level content, in teaching order: plain letters first, then one vowel sign at a time, then
 * several signs together, then conjuncts one family at a time, then everything mixed. Puzzle
 * difficulty (tiles, word count, longest word, rarity) only orders levels within a block.
 *
 * Every word is attested in real Bengali text (checked against corpus frequency data) and
 * hand-picked from a vocabulary curated for a child - frequency alone offers verb inflections,
 * word fragments and newspaper register, none of which teach a beginner anything. Each
 * `letters` entry is one akshara: the unit that sits on a wheel tile and fills one grid cell.
 *
 * `teaches` is what this level introduces that no earlier level used - a letter, a vowel sign,
 * or a conjunct - so the app can show it before the board.
 *
 * Two rules constrain what can go here, and `LevelsTest` enforces both:
 *  - a word must be spellable from the tiles using each tile at most once, and every tile
 *    must be used by some word, so the wheel never holds a letter the player cannot spend;
 *  - the words must form a connected crossword. Only two words can pass through one cell,
 *    so three words sharing nothing but the same akshara cannot all be placed: in
 *    চার / কার / চাবি / চাকা, three of the four meet only at চা.
 *
 *
 * Generated by tools/build.py from tools/catalogue.py - do not edit by hand.
 */
object Levels {

    val all: List<Level> = listOf(
        // Block 2, one vowel sign: a single vowel sign per level, introduced one at a time in KAR_ORDER.
        Level(1, listOf("আ", "না", "র", "স", "অ", "ল"), listOf("আনারস", "অলস", "আনা", "আসল", "রস"), block = 2, teaches = listOf("অ", "ল", "আ", "র", "ন", "স", "া")),

        // Block 4, conjuncts: joined consonants, one cluster family at a time.
        Level(2, listOf("ইঁ", "দু", "র", "উ", "ত্ত", "ট", "ই"), listOf("উট", "ইঁদুর", "উত্তর", "দুই"), block = 4, teaches = listOf("ই", "উ", "দ", "ট", "ু", "ঁ", "ত্ত")),
        Level(3, listOf("ঈ", "গ", "ল", "দ", "ম্বা", "রো", "ব্যা"), listOf("ঈগল", "ঈদ", "লম্বা", "রোদ", "ব্যাগ"), block = 4, teaches = listOf("ঈ", "গ", "ো", "ম্ব", "ব্য")),

        // Block 3, vowel signs together: several signs in one word, all of them already taught.
        Level(4, listOf("ঊ", "নি", "শ", "না", "তা", "ষা", "রা"), listOf("ঊনিশ", "ঊষা", "নাশতা", "তারা", "রানি"), block = 3, teaches = listOf("ঊ", "ত", "শ", "ষ", "ি")),
        Level(5, listOf("দ", "ক্ষি", "ণ", "ঋ", "তু", "সে", "চাঁ"), listOf("ঋণ", "ঋতু", "সেতু", "দক্ষিণ", "চাঁদ"), block = 4, teaches = listOf("ঋ", "চ", "ণ", "ে", "ক্ষ")),
        Level(6, listOf("ও", "জ", "ন", "ক", "ঠি", "এ", "ঠা"), listOf("এক", "ওজন", "কঠিন", "জন", "ওঠা"), block = 3, teaches = listOf("ক", "এ", "ও", "জ", "ঠ")),
        Level(7, listOf("ক", "ল", "ম", "লা", "সি", "ফি"), listOf("কলম", "কফি", "কমলা", "কমল", "কলা", "কলসি", "কম", "কল"), block = 3, teaches = listOf("ম", "ফ")),
        Level(8, listOf("খা", "বা", "র", "খ", "ব", "লা", "খে"), listOf("খালা", "খাবার", "খেলা", "খবর", "বলা"), block = 3, teaches = listOf("ব", "খ")),
        Level(9, listOf("গা", "জ", "র", "গ", "ম", "ল"), listOf("গাজর", "গরম", "গাল", "গম", "জল"), block = 2),
        Level(10, listOf("ঘ", "র", "বা", "ড়ি", "ট", "ঘা"), listOf("ঘড়ি", "ঘট", "ঘরবাড়ি", "ঘাট", "ঘর"), block = 3, teaches = listOf("ঘ", "ড়")),
        Level(11, listOf("চি", "ঠি", "প", "ত্র", "ল", "চু"), listOf("চিল", "চুল", "চিঠি", "চিঠিপত্র", "চুপ"), block = 4, teaches = listOf("প", "ত্র")),
        Level(12, listOf("ছা", "গ", "ল", "রা", "খা", "তা", "ক"), listOf("ছাগল", "ছাতা", "রাখাল", "খাল", "করা", "লতা"), block = 2, teaches = listOf("ছ")),
        Level(13, listOf("জা", "হা", "জ", "গ", "ত", "মা", "তি"), listOf("জাহাজ", "জামা", "জগত", "হাত", "হাতি"), block = 3, teaches = listOf("হ")),
        Level(14, listOf("ঝ", "ল", "ক", "বি", "তা", "ড়", "ঝা"), listOf("ঝড়", "ঝলক", "ঝাল", "কবিতা", "বিল"), block = 3, teaches = listOf("ঝ")),
        Level(15, listOf("টি", "কি", "ট", "মে", "টো", "য়া", "য়ে"), listOf("টিকিট", "টমেটো", "টিয়া", "মেয়ে"), block = 3, teaches = listOf("য়")),
        Level(16, listOf("ঠি", "কা", "না", "বৈ", "ঠ", "ক", "শো"), listOf("ঠিকানা", "ঠিক", "বৈঠক", "শোনা"), block = 3, teaches = listOf("ৈ")),
        Level(17, listOf("ডা", "লি", "ম", "বি", "ড়া", "ল", "ডি"), listOf("ডিম", "ডালিম", "ডাল", "বিড়াল"), block = 3, teaches = listOf("ড")),
        Level(18, listOf("ঢো", "ল", "ঢা", "কা", "লা", "বাং"), listOf("ঢোল", "ঢাল", "ঢোকা", "ঢালা", "বাংলা"), block = 3, teaches = listOf("ঢ", "ং")),
        Level(19, listOf("তো", "য়া", "লে", "লা", "তা", "খা"), listOf("তোয়ালে", "তোলা", "তালা", "লেখা", "খাতা"), block = 3),
        Level(20, listOf("পা", "ঠ", "শা", "লা", "থা", "কা", "মা"), listOf("থাকা", "থালা", "পাঠশালা", "মাঠ"), block = 2, teaches = listOf("থ")),
        Level(21, listOf("দি", "ন", "রা", "ত", "দু", "ধ", "ভা"), listOf("দিনরাত", "দুধভাত", "দুধ", "দিন", "ভাত"), block = 3, teaches = listOf("ভ", "ধ")),
        Level(22, listOf("পা", "য়", "রা", "ধ", "নী", "ধো"), listOf("ধরা", "ধনী", "পায়রা", "ধোপা"), block = 3, teaches = listOf("ী")),

        // Block 1, plain letters: consonants and independent vowels on their own, no signs at all.
        Level(23, listOf("ন", "গ", "দ", "র", "ম", "জ"), listOf("নগদ", "নরম", "নজর", "নগর", "দম"), block = 1),
        Level(24, listOf("পে", "ন্সি", "ল", "প", "ক", "ট"), listOf("পেন্সিল", "পেট", "পলক", "পটল", "টক"), block = 4, teaches = listOf("ন্স")),
        Level(25, listOf("ফ", "ল", "ক", "স", "ফু", "ড়িং"), listOf("ফুল", "ফল", "ফলক", "ফড়িং", "ফসল"), block = 3),
        Level(26, listOf("বা", "স", "ন", "ব"), listOf("বন", "বস", "বাস", "বাসন", "সব"), block = 2),
        Level(27, listOf("ক", "ড়া", "ই", "ভা", "লু", "ষা", "ঙা"), listOf("ভাই", "ভাষা", "কড়াই", "ভালুক", "ভাঙা"), block = 3, teaches = listOf("ঙ")),
        Level(28, listOf("মা", "খ", "ন", "মৌ", "ছি", "মু"), listOf("মাখন", "মৌমাছি", "মাছি", "মুখ", "নখ"), block = 3, teaches = listOf("ৌ")),
        Level(29, listOf("গ", "ণি", "ত", "ব", "ল", "য", "ন্ত্র"), listOf("যন্ত্র", "যত", "গণিত", "বগল", "যব"), block = 4, teaches = listOf("য", "ন্ত্র")),
        Level(30, listOf("রা", "ন্না", "ঘ", "র", "ত", "ন"), listOf("রতন", "রান্নাঘর", "রাত", "রান্না", "ঘন"), block = 4, teaches = listOf("ন্ন")),
        Level(31, listOf("ব", "দ", "ল", "ণ", "লা", "ঠি", "ন"), listOf("লাঠি", "লাল", "বদল", "দল", "লবণ", "নদ"), block = 3),
        Level(32, listOf("শী", "ত", "কা", "ল", "হা", "র"), listOf("শীত", "শীতকাল", "শীতল", "হালকা", "তরল"), block = 3),
        Level(33, listOf("স", "ড়", "ক", "ফ", "ল", "কা", "ষাঁ"), listOf("সড়ক", "সফল", "ষাঁড়", "সকাল", "সকল"), block = 2),
        Level(34, listOf("হা", "ত", "ঘ", "ড়ি", "সি", "হাঁ", "স"), listOf("হাসি", "হাতঘড়ি", "হাঁড়ি", "হাঁস"), block = 3)
    )

    val count: Int get() = all.size

    /**
     * Whether the catalogue runs the whole way through the teaching order rather than stopping
     * part-way. Several tests only mean something about a finished syllabus - that it reaches
     * every letter, that boards get fuller as it advances, that most levels are review - and
     * this is what tells them whether they are looking at one. Only block 1 is written at the
     * moment; the tests come back by themselves as soon as the later blocks do.
     */
    /**
     * Whether this catalogue is the complete teaching syllabus, or a short game cut out of one.
     * Several tests only mean something about the complete thing - that it reaches every
     * letter, that boards get fuller as it advances, that most levels are review - and they
     * check this first. Generated from `catalogue.FULL_SYLLABUS`.
     */
    const val FULL_SYLLABUS = false

    fun byId(id: Int): Level? = all.firstOrNull { it.id == id }
}
