package com.bangla.shobdojot.data

import com.bangla.shobdojot.model.Level

/**
 * Level content, in teaching order: plain letters first, then one vowel sign at a time, then
 * several signs together, then conjuncts one family at a time, then everything mixed. Puzzle
 * difficulty (tiles, word count, longest word, rarity) only orders levels within a block.
 *
 * Every word is attested in real Bengali text (checked against corpus frequency data) and
 * hand-picked from a vocabulary curated for a child - frequency alone offers verb inflections,
 * word fragments and newspaper register, none of which teach a beginner anything. Each
 * `letters` entry is one akshara: the unit that sits on a wheel tile and fills one grid cell.
 *
 * `teaches` is what this level introduces that no earlier level used - a letter, a vowel sign,
 * or a conjunct - so the app can show it before the board.
 *
 * Two rules constrain what can go here, and `LevelsTest` enforces both:
 *  - a word must be spellable from the tiles using each tile at most once, and every tile
 *    must be used by some word, so the wheel never holds a letter the player cannot spend;
 *  - the words must form a connected crossword. Only two words can pass through one cell,
 *    so three words sharing nothing but the same akshara cannot all be placed: in
 *    চার / কার / চাবি / চাকা, three of the four meet only at চা.
 *
 *
 * Generated by tools/build.py from tools/catalogue.py - do not edit by hand.
 */
object Levels {

    val all: List<Level> = listOf(
        // Block 1, plain letters: consonants and independent vowels on their own, no signs at all.
        Level(1, listOf("ক", "ল", "ম"), listOf("কলম", "কম", "কল"), block = 1, teaches = listOf("ল", "ক", "ম")),
        Level(2, listOf("ক", "ল", "ম", "আ"), listOf("কলম", "কম", "কল", "আম"), block = 1, teaches = listOf("আ")),
        Level(3, listOf("ক", "ল", "ম", "এ"), listOf("কলম", "এক", "কম", "কল"), block = 1, teaches = listOf("এ")),
        Level(4, listOf("ক", "ম", "ল", "ফ"), listOf("ফল", "কমল", "ফলক"), block = 1, teaches = listOf("ফ")),
        Level(5, listOf("ক", "ল", "ম", "অ", "ত"), listOf("কলম", "অতল", "কম", "কল"), block = 1, teaches = listOf("অ", "ত")),
        Level(6, listOf("ব", "দ", "ল"), listOf("বদল", "দল", "বল"), block = 1, teaches = listOf("ব", "দ")),
        Level(7, listOf("ক", "দ", "ম", "ঈ"), listOf("ঈদ", "কদম", "দম"), block = 1, teaches = listOf("ঈ")),
        Level(8, listOf("স", "ব", "ক"), listOf("সব", "বস", "বক"), block = 1, teaches = listOf("স")),
        Level(9, listOf("স", "ব", "ই"), listOf("সব", "বই", "বস"), block = 1, teaches = listOf("ই")),
        Level(10, listOf("স", "ক", "ল", "র"), listOf("কর", "সকল", "সরল"), block = 1, teaches = listOf("র"))
    )

    val count: Int get() = all.size

    /**
     * Whether the catalogue runs the whole way through the teaching order rather than stopping
     * part-way. Several tests only mean something about a finished syllabus - that it reaches
     * every letter, that boards get fuller as it advances, that most levels are review - and
     * this is what tells them whether they are looking at one. Only block 1 is written at the
     * moment; the tests come back by themselves as soon as the later blocks do.
     */
    val spansSyllabus: Boolean get() = all.map { it.block }.distinct().size == 5

    fun byId(id: Int): Level? = all.firstOrNull { it.id == id }
}
