#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Level pipeline CLI.

    python3 tools/build.py check              validate the catalogue, print the ramp
    python3 tools/build.py build              regenerate both builds' level tables
    python3 tools/build.py show 64            print one level's board
    python3 tools/build.py discover প্রজাপতি   what else can this word's tiles spell?

`check` exits non-zero when anything is wrong, so it works in CI. After `build`, run the
Kotlin tests (`cd bengali-word-game && ./gradlew test`) — they re-verify the same invariants
against the app's own generator rather than this Python mirror of it.
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))

from bangla import HASANTA, conjunct_tiles, render, split_aksharas   # noqa: E402
from catalogue import CATALOGUE, ordered_levels                      # noqa: E402

REPO = pathlib.Path(__file__).resolve().parent.parent
KOTLIN = REPO / 'bengali-word-game/app/src/main/java/com/bangla/shobdojot/data/Levels.kt'
WEB = REPO / 'docs/index.html'

KOTLIN_HEADER = '''package com.bangla.shobdojot.data

import com.bangla.shobdojot.model.Level

/**
 * Level content, ordered by difficulty: tile count, word count, how long the longest word
 * is, whether conjunct tiles appear, and how common the words are.
 *
 * Every word is attested in real Bengali text (checked against corpus frequency data) and
 * hand-picked — frequency lists happily offer verb inflections and word fragments, which
 * make poor puzzles. Each `letters` entry is one akshara: the unit that sits on a wheel tile
 * and fills one grid cell.
 *
 * Two rules constrain what can go here, and `LevelsTest` enforces both:
 *  - a word must be spellable from the tiles using each tile at most once, and every tile
 *    must be used by some word, so the wheel never holds a letter the player cannot spend;
 *  - the words must form a connected crossword. Only two words can pass through one cell,
 *    so three words sharing nothing but the same akshara cannot all be placed: in
 *    চার / কার / চাবি / চাকা, three of the four meet only at চা.
 *
 * `extras` are words the same tiles can spell that are not on the board; finding one fills
 * the chest instead of the grid.
 *
 * Generated by tools/build.py from tools/catalogue.py — do not edit by hand.
 */
object Levels {

    val all: List<Level> = listOf('''

KOTLIN_FOOTER = '''    )

    val count: Int get() = all.size

    fun byId(id: Int): Level? = all.firstOrNull { it.id == id }
}'''

FIRST_LINE = 'Easiest first: three tiles, short everyday words.'
FIRST_CONJUNCT = 'The first level with a conjunct tile: ন্ত is one letter unit, one tile.'
FIRST_BIG = 'The first five-tile board. Six-tile boards close out the game.'


def milestones(levels):
    """
    Which level ids deserve a comment. Difficulty ordering interleaves the categories, so a
    category header would lie about what follows it; a "first of its kind" note does not.
    """
    marks = {1: FIRST_LINE}
    for i, level in enumerate(levels, 1):
        if any(HASANTA in t for t in level['tiles']) and FIRST_CONJUNCT not in marks.values():
            marks[i] = FIRST_CONJUNCT
        if len(level['tiles']) >= 5 and FIRST_BIG not in marks.values():
            marks[i] = FIRST_BIG
    return marks


def emit(levels):
    marks = milestones(levels)
    kt, js = [KOTLIN_HEADER], ['const LEVELS = [']

    for i, level in enumerate(levels, 1):
        note = marks.get(i)
        if note and i != 1:
            kt.append('')
            js.append('')
        if note:
            kt.append(f'        // {note}')
            js.append(f'  // {note}')
        tiles = ', '.join(f'"{t}"' for t in level['tiles'])
        words = ', '.join(f'"{w}"' for w in level['words'])
        extras = ', '.join(f'"{w}"' for w in level['extras'])
        # Levels whose tiles spell nothing extra simply omit the argument.
        kt_extras = f', extras = listOf({extras})' if extras else ''
        js_extras = f', extras: [{extras}]' if extras else ''
        kt.append(f'        Level({i}, listOf({tiles}), listOf({words}){kt_extras}),')
        js.append(f'  {{ id: {i}, letters: [{tiles}], words: [{words}]{js_extras} }},')

    kt[-1] = kt[-1].rstrip(',')
    js[-1] = js[-1].rstrip(',')
    kt.append(KOTLIN_FOOTER)
    js.append('];')
    return '\n'.join(kt) + '\n', '\n'.join(js)


def write_builds(levels):
    kotlin_src, js_src = emit(levels)

    before_kt = KOTLIN.read_text(encoding='utf-8') if KOTLIN.exists() else ''
    KOTLIN.write_text(kotlin_src, encoding='utf-8')

    html = WEB.read_text(encoding='utf-8')
    start = html.index('const LEVELS = [')
    end = html.index('];', start) + 2
    before_web = html
    WEB.write_text(html[:start] + js_src + html[end:], encoding='utf-8')

    return (before_kt != kotlin_src,
            before_web != WEB.read_text(encoding='utf-8'))


def report(levels, failures):
    print(f'{len(levels)} levels valid, {len(failures)} rejected\n')
    for words, problems in failures:
        print(f'REJECTED  {" ".join(words)}')
        for p in problems:
            print(f'            {p}')
    if failures:
        print()

    print('  id  tiles  words  longest  board   content')
    for i, level in enumerate(levels, 1):
        longest = max(len(split_aksharas(w)) for w in level['words'])
        mark = ' +conjunct' if conjunct_tiles(level['tiles']) else ''
        rows, cols = level['size']
        print(f'  {i:<3} {len(level["tiles"]):<6} {len(level["words"]):<6} {longest:<8} '
              f'{rows}x{cols:<5} {" ".join(level["words"])}{mark}')

    words = {w for level in levels for w in level['words']}
    aksharas = {a for w in words for a in split_aksharas(w)}
    print(f'\n{len(words)} distinct words, {len(aksharas)} distinct aksharas, '
          f'largest level {max(len(l["words"]) for l in levels)} words '
          f'/ {max(len(l["tiles"]) for l in levels)} tiles')


def main(argv):
    command = argv[0] if argv else 'check'

    if command == 'discover':
        if len(argv) < 2:
            print('usage: build.py discover <bengali word>')
            return 2
        from wordpool import discover
        print(discover(argv[1]))
        return 0

    levels, failures = ordered_levels()

    if command == 'check':
        report(levels, failures)
        if failures:
            print('\ncheck FAILED')
            return 1
        if len(levels) != len(CATALOGUE):
            print('\ncheck FAILED: lost levels between catalogue and output')
            return 1
        print('check ok')
        return 0

    if command == 'build':
        if failures:
            report(levels, failures)
            print('\nrefusing to build with rejected levels')
            return 1
        kt_changed, web_changed = write_builds(levels)
        print(f'{len(levels)} levels written')
        print(f'  {KOTLIN.relative_to(REPO)}  {"updated" if kt_changed else "unchanged"}')
        print(f'  {WEB.relative_to(REPO)}  {"updated" if web_changed else "unchanged"}')
        print('\nnow run: cd bengali-word-game && ./gradlew test')
        return 0

    if command == 'show':
        if len(argv) < 2 or not argv[1].isdigit():
            print('usage: build.py show <level id>')
            return 2
        index = int(argv[1])
        if not 1 <= index <= len(levels):
            print(f'no level {index}; there are {len(levels)}')
            return 2
        level = levels[index - 1]
        print(f'level {index}: tiles {" ".join(level["tiles"])}')
        print(f'words: {" ".join(level["words"])}\n')
        print(render(level['occupied']))
        return 0

    print(__doc__)
    return 2


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
