#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Level pipeline CLI.

    python3 tools/build.py check              validate the catalogue, print the ramp
    python3 tools/build.py build              regenerate both builds' level tables
    python3 tools/build.py show 64            print one level's board
    python3 tools/build.py curriculum         the syllabus: what each level teaches
    python3 tools/build.py slots              recording and illustration work, in order
    python3 tools/build.py voice              the pronunciation manifest, as JS
    python3 tools/build.py discover প্রজাপতি   what else can this word's tiles spell?

`check` exits non-zero when anything is wrong, so it works in CI. After `build`, run the
Kotlin tests (`cd bengali-word-game && ./gradlew test`) - they re-verify the same invariants
against the app's own generator rather than this Python mirror of it.
"""
import itertools
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))

from bangla import conjunct_tiles, render, split_aksharas            # noqa: E402
from catalogue import (CATALOGUE, CAVEAT, FULL_SYLLABUS, GLOSS, MAX_NEW_UNITS,   # noqa: E402
                       SHARED, ordered_levels)
from curriculum import (BLOCKS, NOT_TAUGHT, alphabet,                  # noqa: E402
                        unit_label)
from vocabulary import theme_of, words as pool_words                                       # noqa: E402

REPO = pathlib.Path(__file__).resolve().parent.parent
KOTLIN = REPO / 'bengali-word-game/app/src/main/java/com/bangla/shobdojot/data/Levels.kt'
SOURCE = REPO / 'src/shobdojot.html'      # authored, with every comment
WORKER = REPO / 'docs/sw.js'              # offline cache; its version is stamped below
WEB = REPO / 'docs/index.html'            # built, comments stripped
# The same page with the document wrapper taken off, for hosts that supply their own
# <!doctype>/<html>/<head>/<body> - claude.ai artifacts among them. Generated, never edited:
# a hand-maintained copy of a 2000-line file goes stale the first time the original changes.
LIVE = REPO / 'docs/live.html'

KOTLIN_HEADER = '''package com.bangla.shobdojot.data

import com.bangla.shobdojot.model.Level

/**
 * Level content, in teaching order: plain letters first, then one vowel sign at a time, then
 * several signs together, then conjuncts one family at a time, then everything mixed. Puzzle
 * difficulty (tiles, word count, longest word, rarity) only orders levels within a block.
 *
 * Every word is attested in real Bengali text (checked against corpus frequency data) and
 * hand-picked from a vocabulary curated for a child - frequency alone offers verb inflections,
 * word fragments and newspaper register, none of which teach a beginner anything. Each
 * `letters` entry is one akshara: the unit that sits on a wheel tile and fills one grid cell.
 *
 * `teaches` is what this level introduces that no earlier level used - a letter, a vowel sign,
 * or a conjunct - so the app can show it before the board.
 *
 * Two rules constrain what can go here, and `LevelsTest` enforces both:
 *  - a word must be spellable from the tiles using each tile at most once, and every tile
 *    must be used by some word, so the wheel never holds a letter the player cannot spend;
 *  - the words must form a connected crossword. Only two words can pass through one cell,
 *    so three words sharing nothing but the same akshara cannot all be placed: in
 *    চার / কার / চাবি / চাকা, three of the four meet only at চা.
 *
 *
 * Generated by tools/build.py from tools/catalogue.py - do not edit by hand.
 */
object Levels {

    val all: List<Level> = listOf('''

KOTLIN_FOOTER = '''    )

    val count: Int get() = all.size

    /**
     * Whether the catalogue runs the whole way through the teaching order rather than stopping
     * part-way. Several tests only mean something about a finished syllabus - that it reaches
     * every letter, that boards get fuller as it advances, that most levels are review - and
     * this is what tells them whether they are looking at one. Only block 1 is written at the
     * moment; the tests come back by themselves as soon as the later blocks do.
     */
    /**
     * Whether this catalogue is the complete teaching syllabus, or a short game cut out of one.
     * Several tests only mean something about the complete thing - that it reaches every
     * letter, that boards get fuller as it advances, that most levels are review - and they
     * check this first. Generated from `catalogue.FULL_SYLLABUS`.
     */
    const val FULL_SYLLABUS = %s

    fun byId(id: Int): Level? = all.firstOrNull { it.id == id }
}'''

def milestones(levels):
    """
    Which level ids deserve a comment. Levels now run in syllabus order, so the honest marker
    is the start of each block - it says exactly what changes from here on.
    """
    marks, seen = {}, set()
    for i, level in enumerate(levels, 1):
        block = level['block']
        if block not in seen:
            seen.add(block)
            info = BLOCKS[block]
            marks[i] = f'Block {block}, {info["name"]}: {info["goal"]}.'
    return marks


def emit(levels):
    marks = milestones(levels)
    kt, js = [KOTLIN_HEADER], ['const LEVELS = [']

    for i, level in enumerate(levels, 1):
        note = marks.get(i)
        if note and i != 1:
            kt.append('')
            js.append('')
        if note:
            kt.append(f'        // {note}')
            js.append(f'  // {note}')
        tiles = ', '.join(f'"{t}"' for t in level['tiles'])
        words = ', '.join(f'"{w}"' for w in level['words'])
        teaches = ', '.join(f'"{symbol}"' for _, symbol in level['teaches'])
        # A level that introduces nothing new simply omits the argument rather than passing an
        # empty list.
        kt_teaches = f', teaches = listOf({teaches})' if teaches else ''
        # The board, laid out here rather than in the page. It used to be generated at
        # runtime, which meant the placer existed twice - once in Python for the checks and
        # once in JavaScript for the game - and the two could drift silently. Emitting it
        # leaves one implementation, lets the search be exhaustive (5040 orderings for a
        # seven-word level, three seconds for all 118) instead of a heuristic cheap enough to
        # run on page load, and costs the page nothing at startup.
        cells = level['placed']
        board = ', '.join(
            '{w:"%s",c:[%s]}' % (word, ','.join(f'[{r},{c}]' for r, c in cs))
            for word, cs in cells)
        kt.append(f'        Level({i}, listOf({tiles}), listOf({words}), '
                  f'block = {level["block"]}{kt_teaches}),')
        # Only what the page cannot work out for itself. The word list is the board read
        # back, and the grid size is how far the cells reach, so `boardOf` derives both -
        # emitting them too was 15 KB of the same facts twice. `islands` was emitted, carried
        # through `boardOf` and never read by anything. `teaches` likewise: 58 levels carried
        # it and no line of the page ever looked at it. The Kotlin build still gets the full
        # record; the parked app has no board placer to derive from.
        js.append(f'  {{ id: {i}, letters: [{tiles}], '
                  f'block: {level["block"]}, board: [{board}] }},')

    kt[-1] = kt[-1].rstrip(',')
    js[-1] = js[-1].rstrip(',')
    kt.append(KOTLIN_FOOTER % ('true' if FULL_SYLLABUS else 'false'))
    js.append('];')
    # Nothing may follow the closing bracket. `write_builds` splices this in by replacing
    # everything from `const LEVELS = [` to the first `];` it finds after it, so anything
    # emitted past that point is left behind on the next build instead of being replaced -
    # which, for a `const`, means a duplicate declaration and a page that will not parse.
    return '\n'.join(kt) + '\n', '\n'.join(js)


def minify(html):
    """
    The page with its comments taken out. 260 lines of them, and they belong in the source
    rather than in every download: this saves about 10 KB gzipped, 8% of what crosses the wire.

    Deliberately timid. Only whole-line comments and whole-line block comments go, never a
    trailing one - `//` and `/*` appear inside strings and regular expressions in this file,
    and a minifier clever enough to tell the difference is a minifier clever enough to be
    wrong. Indentation is stripped only from script and style lines, and only because no
    template literal in the page spans a line, so no output string can change. Everything is
    checked afterwards against the built file, not the source, so a mistake here fails the
    tests rather than shipping.
    """
    out, in_block, in_script, in_style = [], False, False, False
    for line in html.split('\n'):
        bare = line.strip()
        if bare == '<script>':
            in_script = True
        elif bare == '</script>':
            in_script = False
        elif bare == '<style>':
            in_style = True
        elif bare == '</style>':
            in_style = False

        if in_block:
            if '*/' in bare:
                in_block = False
                if bare.split('*/', 1)[1].strip():      # code after the close: keep the line
                    out.append(line.split('*/', 1)[1].rstrip())
            continue
        if (in_script or in_style) and bare.startswith('/*') and '*/' not in bare:
            in_block = True
            continue
        if (in_script or in_style) and (bare.startswith('//')
                                        or (bare.startswith('/*') and bare.endswith('*/'))):
            continue
        if not bare:
            if out and not out[-1]:
                continue                                 # never two blank lines running
            out.append('')
            continue
        out.append(bare if (in_script or in_style) else line.rstrip())
    return '\n'.join(out) + '\n'


def write_builds(levels):
    # The web build is the product. The Android app is parked, and it can no longer be
    # generated into honestly: its CrosswordGenerator lays boards out as one connected
    # crossword, which is exactly what the akshara-keyed curriculum cannot be, so writing
    # these levels into Levels.kt would hand it data it cannot place. Reviving the app means
    # porting `cluster_layout` to Kotlin first; until then it keeps the levels it had.
    _, js_src = emit(levels)

    html = SOURCE.read_text(encoding='utf-8')
    if html.count('const LEVELS = [') != 1:
        raise SystemExit('src/shobdojot.html: expected exactly one `const LEVELS = [`')
    start = html.index('const LEVELS = [')
    end = html.index('];', start) + 2
    SOURCE.write_text(html[:start] + js_src + html[end:], encoding='utf-8')

    before_web = WEB.read_text(encoding='utf-8') if WEB.exists() else ''
    built = minify(SOURCE.read_text(encoding='utf-8'))
    WEB.write_text(built, encoding='utf-8')

    # Stamp the offline cache with something that changes whenever the page does. Left to a
    # human this gets forgotten, and a forgotten bump means every returning player keeps the
    # copy they already have - the page updates for new visitors and for nobody else.
    if WORKER.exists():
        worker = WORKER.read_text(encoding='utf-8')
        stamp = f"shobdojot-{len(levels)}-{len(built.encode('utf-8'))}"
        fresh = re.sub(r"const VERSION = '[^']*';", f"const VERSION = '{stamp}';", worker, count=1)
        if fresh != worker:
            WORKER.write_text(fresh, encoding='utf-8')

    before_live = LIVE.read_text(encoding='utf-8') if LIVE.exists() else ''
    live_src = unwrap(built)
    LIVE.write_text(live_src, encoding='utf-8')

    return (False, before_web != built, before_live != live_src)


def unwrap(html):
    """The page's <title>, <style> and body, with the document wrapper removed.

    An embedding host wraps what it is given in its own <!doctype>/<head>/<body>, so shipping
    those tags a second time is at best ignored and at worst reparsed into something else. The
    <title> is kept because it names the page wherever it is published; the rest of <head> is
    metadata for a standalone URL - viewport, icons, Open Graph - which the host provides or
    does not want.
    """
    lines = html.split('\n')

    def only(pred, what):
        hits = [i for i, l in enumerate(lines) if pred(l)]
        if len(hits) != 1:
            raise SystemExit(f'docs/index.html: expected exactly one {what}, found {len(hits)}')
        return hits[0]

    title = only(lambda l: l.startswith('<title>'), '<title> line')
    style = only(lambda l: l.strip() == '<style>', '<style> line')
    head_end = only(lambda l: l.strip() == '</head>', '</head> line')
    body = only(lambda l: l.strip() == '<body>', '<body> line')
    if body != head_end + 1:
        raise SystemExit('docs/index.html: <body> is expected on the line after </head>')

    end = len(lines)
    while lines[end - 1].strip() in ('', '</html>', '</body>'):
        end -= 1

    # The artifact gallery shows the title as the page's name, where the standalone page's
    # search-engine suffix reads as filler.
    name = lines[title].replace(' - Bengali Word Puzzle', '')
    out = '\n'.join([name] + lines[style:head_end] + lines[body + 1:end]) + '\n'

    for tag in ('<!doctype', '<html', '<head>', '</head>', '<body>', '</body>', '</html>'):
        if tag in out.lower():
            raise SystemExit(f'docs/live.html: {tag} survived the unwrap')
    if 'const LEVELS = [' not in out or '<style>' not in out:
        raise SystemExit('docs/live.html: unwrap dropped something it should have kept')
    return out


def ring_run(order, word):
    """Does `word` sit in an unbroken run around the ring, in the order it is spelled?

    Mirrors `ringRun` in the page: a run may wrap past the last tile, and it counts in either
    direction, because a ring is read both ways.
    """
    n = len(order)
    at = {a: i for i, a in enumerate(order)}
    spots = [at.get(a) for a in split_aksharas(word)]
    if any(s is None for s in spots) or len(spots) < 2:
        return False
    step = lambda i: ((spots[i + 1] - spots[i]) + n) % n
    ahead = all(step(i) == 1 for i in range(len(spots) - 1))
    behind = all(step(i) == n - 1 for i in range(len(spots) - 1))
    return ahead or behind


def ring_can_hide(tiles, words):
    """Is there any wheel arrangement that spells out none of the words of 3 or more letters?

    Two-letter words are exempt: they need two tiles side by side, a ring of n tiles has n
    neighbouring pairs, and a board of n two-letter words needs all of them - something has to
    touch. Rotations of the same ring are the same wheel, so one tile is held fixed.
    """
    longs = [w for w in words if len(split_aksharas(w)) >= 3]
    if not longs or len(tiles) < 3:
        return True
    first, rest = tiles[0], tiles[1:]
    for perm in itertools.permutations(rest):
        order = [first] + list(perm)
        if not any(ring_run(order, w) for w in longs):
            return True
    return False


def report(levels, failures):
    print(f'{len(levels)} levels valid, {len(failures)} rejected\n')
    for words, problems in failures:
        print(f'REJECTED  {" ".join(words)}')
        for p in problems:
            print(f'            {p}')
    if failures:
        print()

    print('  id  blk  tiles  words  longest  board   teaches      content')
    for i, level in enumerate(levels, 1):
        longest = max(len(split_aksharas(w)) for w in level['words'])
        mark = ' +conjunct' if conjunct_tiles(level['tiles']) else ''
        rows, cols = level['size']
        new = ' '.join(symbol for _, symbol in level['teaches'])
        print(f'  {i:<3} {level["block"]:<4} {len(level["tiles"]):<6} '
              f'{len(level["words"]):<6} {longest:<8} {rows}x{cols:<5} {new:<12} '
              f'{" ".join(level["words"])}{mark}')

    words = {w for level in levels for w in level['words']}
    aksharas = {a for w in words for a in split_aksharas(w)}
    print(f'\n{len(words)} distinct words, {len(aksharas)} distinct aksharas, '
          f'largest level {max(len(l["words"]) for l in levels)} words '
          f'/ {max(len(l["tiles"]) for l in levels)} tiles')

    # Coverage. The whole point of a teaching order is that a learner who finishes reaches the
    # end of the alphabet, so a gap here is a broken promise rather than a missing nicety -
    # once there is a whole teaching order to finish. While the syllabus stops inside block 1
    # the gaps are simply the blocks that are not written yet, and are reported rather than
    # treated as failures.
    taught = {u for level in levels for u in level['teaches']}
    missing = [u for u in alphabet() if u not in taught]
    print(f'\nalphabet: {len(alphabet()) - len(missing)} of {len(alphabet())} units taught'
          f' ({len(NOT_TAUGHT)} excluded by design: {" ".join(NOT_TAUGHT)})')
    if missing and FULL_SYLLABUS:
        print(f'  NOT TAUGHT ANYWHERE ({len(missing)}):')
        for unit in missing:
            print(f'    {unit_label(unit)}')
    elif missing:
        print(f'  {len(missing)} still to come. These ten levels are a game rather than a '
              f'syllabus (catalogue.FULL_SYLLABUS),\n  so this is what is not written yet '
              f'rather than a gap in something that claims to be finished.')

    # Each level is named after a letter, and the board has to be about that letter: more of
    # its words start with it than with any other single letter. Both halves are worth printing
    # - the words that carry the letter, and the ones that are only there to hold the crossword
    # together, since a board of nothing but same-letter words often will not lay out at all.
    print('\nalphabet levels:')
    for i, level in enumerate(levels, 1):
        letters = level.get('letters', '')
        own = [w for w in level['words']
               if any(split_aksharas(w)[0].startswith(x) for x in letters)]
        rest = [w for w in level['words'] if w not in own]
        print(f'  level {i:<3} {letters:3} {len(own)} of {len(level["words"])} words '
              f'({" ".join(own)})' + (f'  + {" ".join(rest)}' if rest else ''))

    # Which letters the curriculum covers, and how far each one's kar series goes. Worth
    # stating out loud rather than assuming: "we did ক through হ" is easy to say and easy to be
    # wrong about, and the uploaded curriculum in fact has no ঠ, ঢ, য or ষ at all.
    series = {}
    for level in levels:
        key = level.get('letters', '')
        base = key.split('-')[0][0] if key else '?'
        series.setdefault(base, []).append(key)
    letters = [c for kind, c in alphabet() if kind in ('vowel', 'consonant')]
    missing = [c for c in letters if c not in series]
    print(f'\nalphabet run: {len(series)} base letters have at least one level, '
          f'{len(levels)} levels in all')
    for base in letters:
        if base in series:
            print(f'    {base}  {len(series[base])}: {" ".join(series[base])}')
    if missing:
        print(f'  {len(missing)} letters have no level at all: {" ".join(missing)}')
        print('    (ঙ ঞ ণ ড় ঢ় য় are left out by design - no Bengali word begins with them)')

    # Whether the game gets harder, which for 156 levels in alphabet order is not a given. The
    # measures are crude on purpose - wheel size, words, conjunct tiles, cells to fill - but
    # they are the four things that decide how long a level takes, and printing them in ten
    # stretches makes a flat run obvious at a glance. It was flat when this was written: 6.6
    # tiles in the first tenth against 6.2 in the last, and the two hardest levels in the game
    # sat at 11 and 13 because ঐ and ঔ fall there in the alphabet. They were moved to the end.
    import statistics
    HASANTA = '\u09cd'
    rows = []
    for level in levels:
        ws = level['words']
        rows.append((len(level['tiles']), len(ws),
                     sum(1 for w in ws for a in split_aksharas(w) if HASANTA in a),
                     sum(len(split_aksharas(w)) for w in ws)))
    tenths = [rows[i * len(rows) // 10:(i + 1) * len(rows) // 10] for i in range(10)]
    print('\ndoes it get harder? the game in ten stretches, first to last')
    for col, label in enumerate(('wheel size', 'words', 'conjunct tiles', 'cells to fill')):
        line = '  '.join(f'{statistics.mean([r[col] for r in t]):4.1f}' for t in tenths)
        print(f'  {label:<16}{line}')

    # The words that need art direction, from the curriculum's own notes. Every word is
    # supposed to be something a picture can show; the ones that are not carry a note saying
    # how to draw them, or saying plainly that they cannot be drawn. Printing them here is the
    # only reason those notes are worth writing down - a note nobody reads is a note nobody
    # acts on, and these are the words an illustrator will get stuck on.
    noted = [(i, w) for i, level in enumerate(levels, 1)
             for w in level['words'] if w in CAVEAT]
    print(f'\nwords needing art direction: {len(noted)} of {sum(len(l["words"]) for l in levels)}')
    for i, w in noted:
        print(f'  level {i:<4} {w:<12} {GLOSS.get(w, "?"):<26} {CAVEAT[w]}')

    # No word set as a puzzle twice. `ordered_levels` rejects any level that breaks it outside
    # the documented list, so this is a count of what the documented list is actually covering
    # rather than a check - it is here so the number cannot grow unnoticed.
    seen, borrowed = {}, []
    for i, level in enumerate(levels, 1):
        for w in level['words']:
            if w in seen:
                borrowed.append((i, w, seen[w]))
            else:
                seen[w] = i
    slots = sum(len(l['words']) for l in levels)
    print(f'\nno repeats: {len(seen)} distinct words across {slots} board slots, '
          f'{len(borrowed)} borrowed by {len({i for i, _, _ in borrowed})} levels')
    for i, word, first in borrowed:
        print(f'  level {i:<3} borrows {word} from level {first}: {SHARED[word]}')
    unused = [w for w in SHARED if w not in {word for _, word, _ in borrowed}]
    if unused:
        print(f'  {len(unused)} SHARED entries no level needs: {" ".join(unused)}')

    # A level that introduces a pile of new material at once is a lecture, not a lesson - in a
    # syllabus. Ten levels that skip from plain letters to conjuncts introduce a great deal per
    # level by construction, and there is nothing to fix, so this only reports while the
    # catalogue is claiming to teach. Level 1 is exempt either way: it has nothing to build on.
    steep = [(i, level) for i, level in enumerate(levels, 1)
             if FULL_SYLLABUS and i > 1
             and len(level['teaches']) > MAX_NEW_UNITS[level['block']]]
    if steep:
        print(f'\n{len(steep)} levels past the first introduce more than their '
              f'block\'s budget:')
        for i, level in steep:
            budget = MAX_NEW_UNITS[level['block']]
            new = ' '.join(unit_label(u) for u in level['teaches'])
            print(f'  level {i:<3} block {level["block"]}  {len(level["teaches"])} > '
                  f'{budget}:  {new}')


def curriculum(levels):
    """The syllabus as a reader sees it: what each block covers and what each level adds."""
    block = None
    for i, level in enumerate(levels, 1):
        if level['block'] != block:
            block = level['block']
            info = BLOCKS[block]
            print(f'\n== Block {block}: {info["name"]} ({info["bn"]}) ==')
            print(f'   {info["goal"]}\n')
        new = ', '.join(unit_label(u) for u in level['teaches']) or '-'
        print(f'  {i:<3} {" ".join(level["words"]):<44} new: {new}')

    taught = [u for level in levels for u in level['teaches']]
    kinds = {}
    for kind, _ in taught:
        kinds[kind] = kinds.get(kind, 0) + 1
    print('\ntaught across the game: ' +
          ', '.join(f'{n} {kind}s' for kind, n in sorted(kinds.items())))
    silent = [i for i, level in enumerate(levels, 1) if not level['teaches']]
    print(f'{len(silent)} levels introduce nothing new (pure review)')

    taught = {u for level in levels for u in level['teaches']}
    missing = [u for u in alphabet() if u not in taught]
    print(f'alphabet: {len(alphabet()) - len(missing)} of {len(alphabet())} units'
          + (', missing ' + ' '.join(s for _, s in missing) if missing else ' - complete'))
    print('excluded by design: ' + ', '.join(f'{s} ({why.split(chr(45))[0].strip()})'
                                             for s, why in NOT_TAUGHT.items()))


def slots(levels):
    """
    The content work this syllabus implies, in the order it would be recorded: every distinct
    word, the level it first appears in, and the theme it was curated under. Audio and a
    picture per word is the bulk of the remaining effort, and it is useless out of order - a
    learner meets level 3 long before level 60.
    """
    first = {}
    for i, level in enumerate(levels, 1):
        for w in level['words']:
            if w not in first:
                first[w] = i

    print(f'{len(first)} words need audio and a picture, in this order:\n')
    print('  level  theme            word')
    for w, i in sorted(first.items(), key=lambda kv: (kv[1], kv[0])):
        print(f'  {i:<6} {str(theme_of(w) or "-"):<16} {w}')

    missing = [w for w in first if theme_of(w) is None]
    if missing:
        print(f'\n{len(missing)} board words are not in the curated pool, so they have no '
              f'theme yet:\n  {" ".join(sorted(missing))}')


def voice(levels):
    """
    The pronunciation manifest: every distinct thing the game says out loud, in the order a
    learner meets it, as a JS object ready to paste over `VOICE_CLIPS` in `docs/index.html`.

    The web build already speaks through the device's own Bengali voice where one exists, and
    stays silent where none does. Recordings replace both: they sound like a person, they are
    paced for a child, and they work on a device with no Bengali voice at all - which includes
    every iPhone. This prints the list to hand to whoever records them.
    """
    words, first = [], {}
    for i, level in enumerate(levels, 1):
        for word in level['words']:
            if word not in first:
                words.append(word)
                first[word] = i

    print('// Pronunciation manifest, generated by tools/build.py voice.')
    print('// One clip per entry, recorded by a Bengali speaker, paced for a child.')
    print(f'// {len(words)} words, in the order a learner meets them. Words only: the game '
          'speaks')
    print('// what a player spells, and a letter on its own is not something it says out loud.')
    print('const VOICE_CLIPS = {')
    for word in words:
        theme = theme_of(word)
        note = f'  // level {first[word]}' + (f', {theme}' if theme else '')
        print(f'  "{word}": "audio/{word}.opus",{note}')
    print('};')
    print(f'\n// {len(words)} clips. Roughly {len(words) * 4 // 1000 + 1} MB as Opus at '
          f'24 kbps, so they fit inside the single-file build as data: URIs.')


def main(argv):
    command = argv[0] if argv else 'check'

    if command == 'discover':
        if len(argv) < 2:
            print('usage: build.py discover <bengali word>')
            return 2
        from wordpool import discover
        print(discover(argv[1]))
        return 0

    levels, failures = ordered_levels()

    if command == 'check':
        report(levels, failures)
        if failures:
            print('\ncheck FAILED')
            return 1
        gaps = [u for u in alphabet()
                if u not in {t for level in levels for t in level['teaches']}]
        if gaps and FULL_SYLLABUS:
            print(f'\ncheck FAILED: {len(gaps)} pieces of the alphabet are never taught')
            return 1
        if len(levels) != len(CATALOGUE):
            print('\ncheck FAILED: lost levels between catalogue and output')
            return 1
        # The letter a level declares has to be the letter it is about. Caught a real one:
        # a level named ধ whose board was থাকা থালা পাঠশালা পানি পাঠ - two থ words and three
        # প ones, which is a প level, and it would have taken three words প's own level needs.
        wrong = []
        for i, level in enumerate(levels, 1):
            letters = level.get('letters', '')
            if not letters:
                wrong.append(f'level {i} declares no letter')
                continue
            own = sum(1 for w in level['words']
                      if any(split_aksharas(w)[0].startswith(x) for x in letters))
            others = {}
            for w in level['words']:
                if any(split_aksharas(w)[0].startswith(x) for x in letters):
                    continue
                head = split_aksharas(w)[0][0]
                others[head] = others.get(head, 0) + 1
            if own < 2:
                wrong.append(f'level {i} ({letters}) has {own} word starting with it')
            elif others and max(others.values()) >= own:
                loud = max(others, key=lambda k: others[k])
                wrong.append(f'level {i} ({letters}) has {own} words to {loud}\'s '
                             f'{others[loud]} - it is a {loud} level')
        if wrong and not FULL_SYLLABUS:
            print('\ncheck FAILED: ' + '; '.join(wrong))
            return 1

        needed = set()
        seen = set()
        for level in levels:
            for w in level['words']:
                if w in seen:
                    needed.add(w)
                seen.add(w)
        stale = sorted(set(SHARED) - needed)
        if stale:
            print(f'\ncheck FAILED: SHARED lists {len(stale)} words no level borrows: '
                  f'{" ".join(stale)}')
            return 1

        # The wheel is scrambled so that no answer is spelled out in sequence around the ring.
        # That only works if some arrangement exists that hides every word, and on a small
        # wheel one may not. Caught a real one: a four-tile ক level - কমল কলম কমলা কলা কম কল -
        # where a four-tile ring has just six possible arrangements and every single one laid
        # one of those words out in ring order. The answer was drawn on the wheel and no
        # amount of scrambling could have hidden it.
        undrawable = []
        for i, level in enumerate(levels, 1):
            if not ring_can_hide(level['tiles'], level['words']):
                undrawable.append(f"level {i} ({level.get('letters', '?')}) on "
                                  f"{len(level['tiles'])} tiles")
        if undrawable:
            print('\ncheck FAILED: no wheel arrangement hides every answer on '
                  + '; '.join(undrawable))
            return 1
        print('check ok')
        return 0

    if command == 'build':
        if failures:
            report(levels, failures)
            print('\nrefusing to build with rejected levels')
            return 1
        kt_changed, web_changed, live_changed = write_builds(levels)
        print(f'{len(levels)} levels written')
        print(f'  {KOTLIN.relative_to(REPO)}  not written - the app is parked, see write_builds')
        print(f'  {WEB.relative_to(REPO)}  {"updated" if web_changed else "unchanged"}')
        print(f'  {LIVE.relative_to(REPO)}  {"updated" if live_changed else "unchanged"}')
        print('\nnow run: cd bengali-word-game && ./gradlew test')
        return 0

    if command == 'curriculum':
        curriculum(levels)
        return 0

    if command == 'slots':
        slots(levels)
        return 0

    if command == 'voice':
        voice(levels)
        return 0

    if command == 'show':
        if len(argv) < 2 or not argv[1].isdigit():
            print('usage: build.py show <level id>')
            return 2
        index = int(argv[1])
        if not 1 <= index <= len(levels):
            print(f'no level {index}; there are {len(levels)}')
            return 2
        level = levels[index - 1]
        print(f'level {index}: tiles {" ".join(level["tiles"])}')
        print(f'words: {" ".join(level["words"])}\n')
        print(render(level['occupied']))
        return 0

    print(__doc__)
    return 2


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
